### ISSUE TITLE
7/25 Hackathon Checklist

### ISSUE THREAD

**Issue by fatima-gov** [usds/us-forms-system#162]
# Forms Hackathon Checklist
**When**: Wednesday, July 25th at 3:00pm - 8:00pm
**Where**: EEOB 474 (Indian Treaty Room)

**Agenda**
- 3:00pm - 3:45pm - Welcome, overview, group pairing
- 3:45pm - 4:00pm - Break / set up
- 4:00pm - 7:00pm - Hacking time!
- 7:00pm - 8:00pm - Demos & Open feedback session

### Logistics / Announcements
- [x] Select 2 - 3 forms of various complexity
- [x] Confirm logistics (date, venue, )
- [x] Announce hackathon at 7/10 staff meeting
- [x] Announce hackathon at 7/24 staff meeting
- [x] Send out invitations including rsvp/waves link
- [x] Order swag stickers and info cards?

### To-do / Hackathon Milestones 
- [x] Merge final docs v1
- [x] Clean up "About the US Forms Library"  #139 
- [x] Fix intro page issues #160 
- [x] Fix progress bar issues #159 
- [x] Create reference docs of components and widget available in the library #107 #154 
- [x] Create "getting started" cheat sheet #161 
- [x] Create slides for welcoming session 
- [x] Create feedback survey 
- [x] Decide how are we collecting feedback from participants during the event (to the extend possible, we should encourage people to take and share their notes and document where they are getting "stuck", decisions they are making, etc)

## Last day checks (Monday and Tuesday before event)
- [x] Review 7/25 Hackathon milestones / audit and close issues 
- [x] Check RSVP link 
- [x] Send out reminders to participants (Including: logistics details, latest agenda, reminders to bring ID, laptops & chargers, what foods/beverages, read-ahead links, etc)
- [x] Place any food catering orders (pizza, water, soda, veggie/cheese plates?)
- [x] Get supplies
   - [x] Extra extension cords, power strips
   - [x] Name tag stickers and markers
   - [x] Index cards, paper, pens, markers, post-it notes, etc
   - [x] Plastics/paper cups, plates, utensils, napkins
- [x] Print hand-outs 
    - Copies of the following: the 3 federal forms, "getting started" cheat sheet, and feedback survey

## On the Day
- [x] Do walk-through of space 2hrs before event start
    - Set-up: 8 tables w/ 10 seats, podium, panel/set-up station
    - Check that WiFi is working
    - Projector / AV are working 
    - Microphone is working 
- [x] Bring all necessary supplies 
- [x] Receive food delivery
- [x] Post signage for directions to hackathon space

## After the event
- [x] Send thank you & feedback survey link to participants 
- [x] Set up time with team to review feedback 
- [ ] Prioritize work post-hackathon and post on board

Anything else?

**Comment by mlazzeri** [comment]
Hey @fatimanoorva ! Will this will be open to non-USDS peeps? How do folks outside of USDS sign up for this? I want to bring myself and a some colleagues:  My emails: marylazzeri@Gmail.com and mlazzeri@hugeinc.com

**Comment by fatimanoorva** [comment]
Hey @mlazzeri! This one is only for USDS (current & alums), so you are more than welcome but would hold off on inviting folks outside USDS for now. We will hold another hackathon in the coming months that will be open to the public. Will definitely keep you posted!

**Comment by mlazzeri** [comment]
Thanks @fatimanoorva !

**Comment by fatimanoorva** [comment]
@mlazzeri No prob! Great reminder to invite alums via crabclaws!

**Comment by dmethvin-gov** [comment]
With the bug discussed in #160 now fixed in the starter app, I've checked the box on the list above. The ticket remains open for the design discussion.
